### ISSUE TITLE
2 _oasis files

### ISSUE THREAD

**Issue by Chris00** [nv-vn/OCamlCSVProvider#1]
I do not understand why there is a second `_oasis` files in `test` instead of having in the toplevel `_oasis`:

```
Executable "test_json_types"
  Build$: flag(tests)
  Path: test
  MainIs: test.ml
  Install: false
  BuildDepends: ppx_csv_provider, csv, lwt, cohttp.lwt
  DataFiles: test.csv
```

**Comment by nv-vn** [comment]
The main reason I was keeping it separate so that it's clear that it's not a part of the main project and so I can just easily remove it with a single command if I chose to. That said, I guess it's probably a better idea to unify it anyways so I'll go ahead and add it in like that.
