### ISSUE TITLE
META file doesn't track dependencies

### ISSUE THREAD

**Issue by rleonid** [nv-vn/OCamlCSVProvider#2]
The [META](https://github.com/nv-vn/OCamlCSVProvider/blob/master/src/META) file that is installed doesn't have the library dependencies listed in [_oasis](https://github.com/nv-vn/OCamlCSVProvider/blob/master/_oasis#L20).

A better way around this problem is to have `oasis` generate the META file during install. AFAIK, this happens when you correctly use `ocaml setup.ml -install`

**Comment by nv-vn** [comment]
AFAIK it's not possible to auto-generate the META file for an executable with OASIS (see: http://oasis.forge.ocamlcore.org/MANUAL-0.4.1.html#plugin-meta-extra). I updated the file manually, but I'm interested in any automated way to do it if there is one.

**Comment by rleonid** [comment]
One could create a library to install with the executable.
