### ISSUE TITLE
does not build on OCaml 4.03.0 and above

### ISSUE THREAD

**Issue by gasche** [nv-vn/OCamlCSVProvider#4]
csv-provider does not build on OCaml 4.03 due to a change in representation of internal parsetree format.

The build failure was spotted by opam-builder, see http://opam.ocamlpro.com/builder/html/csvprovider/csvprovider.1.1/e489f6ebc85defd450ae7df4734ff6e1

```
# File "src/csv_provider.ml", line 34, characters 90-92:
# Error: This expression has type string but an expression was expected of type
#          Asttypes.arg_label
```

On the opam-repository side I am going to make existing releases of csv-provider restricted to OCaml versions (>= 4.02) (before there is no ppx_tools) and (< 4.03) (because of this build failure). A new release compatible with ocaml (>= 4.03) would be welcome.

**Comment by nv-vn** [comment]
Oops, totally forgot that I needed to update my PPXes after 4.03 came out... I'll get to work on this one right now and try to update the other ones whenever I have the time. Thanks for dealing with the OPAM stuff in the meantime!
